name: Waka Readme

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LOC_CHART: False
          SHOW_UPDATED_DATE: False
          COMMIT_MESSAGE: "[ACTION] Automated README Stats"
          COMMIT_BY_ME: True
          LOCALE: "en"
          SHOW_PROFILE_VIEWS: False
          SHOW_LINES_OF_CODE: True
          SHOW_TIMEZONE: False
